### ISSUE TITLE
[Q] How to enable the 8 cores.

### ISSUE THREAD

**Issue by maxime-poulain** [alexax66/kernel_samsung_a3xelte#1]
Hello,

I just built your kernel, and the first thing I could notice is that you enable the full potential of the 7580 board.

Do you mind tellming me which commit/how did you do so ?

Thank you !

**Comment by alexax66** [comment]
Hi
You must apply these commits:

https://github.com/alexax66/kernel_samsung_a3xelte/commit/d541cb2c122942dbd6027ef12d0e6b644c40af00
https://github.com/alexax66/kernel_samsung_a3xelte/commit/8e9311bc25ad61f80cbbc7b7834f4e440485b164
https://github.com/alexax66/kernel_samsung_a3xelte/commit/24e1ffdcd5b51c975f9dea87d17df89a6fe9d93e

**Comment by maxime-poulain** [comment]
Woot!

Thank you very much, I was missing the dts edits...

Do you have any XDA thread for this kernel project ?

**Comment by alexax66** [comment]
I will open special XDA thread for this kernel very soon

**Comment by alexax66** [comment]
Sorry, I missed tell you about this commit to enable the 8 cores:
https://github.com/alexax66/kernel_samsung_a3xelte/commit/5c04b6dc9c87f082529c757a222176c8bccf4da2

**Comment by maxime-poulain** [comment]
No worries,

thank you very much, I will try having fun :P
