### ISSUE TITLE
How to compile kernel ?

### ISSUE THREAD

**Issue by ghost** [alexax66/kernel_samsung_a3xelte#2]
Hello, 
I am interested to compile this kernel for trying it on the A3 but i can't compile it...
Here's what i did : 

- Downloaded `aarch64-linux-android-4.9` from `https://android.googlesource.com/`
- Edited Makefile with the path to the `aarch64-linux-android-4.9`
- `make ARCH=arm64 exynos7580-a3xelte_defconfig`
- `make ARCH=arm64`

But at the end of the task, i just got the kernel (un-compiled) in output folder, and in `boot ` folder, i just got `dt.img`.
Makefile returns me that it can't create `Image `(folder, i think)

Can someone help me to get a boot.img ?
Regards

**Comment by alexax66** [comment]
Hi
I used new toolchain:
https://www.androidfilehost.com/?fid=457095661767130542
(see my commit: https://github.com/alexax66/kernel_samsung_a3xelte/commit/7e3b9297a81274dcee428bce9f7e55f24882d92e )
You need run only build_kernel.sh for start compiling kernel
You can find Image and dt.img in /output/arch/arm64/boot directory after ending compiling 
Good luck!

2017-03-20 23:06 GMT+03:00 Victor Lourme <notifications@github.com>:

**Comment by ghost** [comment]
Ok thanks, i'll try !

Edit: it worked =)
