### ISSUE TITLE
Double tap to wake

### ISSUE THREAD

**Issue by nooneyy** [alexax66/kernel_samsung_a3xelte#3]
Hello, how to enable double tap to wake?
Have you got some commits to it?
Need this to my ENIGMA Rom. 👍

**Comment by alexax66** [comment]
Hi!
See here: https://github.com/Khaon/android_kernel_samsung_a3xelte/commits/a3xelte-mm/drivers/input/touchscreen/imagis_30xxc
and here: https://github.com/alexax66/kernel_samsung_a3xelte/commits/mm/drivers/input/touchscreen

**Comment by nooneyy** [comment]
Hello, thanks!
